# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jkd

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 23-14/1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jkd
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone ${{ secrets.GIT_CLONE_URL }} ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【jkd】'
        run: |
          cd ~/scripts
          node jkd.js
        env:
          JKD_COOKIE: ${{ secrets.JKD_COOKIE }}
          JKD_USER_AGENT: ${{ secrets.JKD_USER_AGENT }}
          JKD_WITHDRAW: ${{ secrets.JKD_WITHDRAW }}
          JKD_FAKE_IOS: ${{ secrets.JKD_FAKE_IOS }}
          JKD_NOTIFY: ${{ secrets.JKD_NOTIFY }}
